DROP SCHEMA IF EXISTS public CASCADE;
CREATE SCHEMA public;
GRANT ALL ON SCHEMA public TO postgres, anon, authenticated, service_role, sandbox_exec;
GRANT USAGE ON SCHEMA cron TO sandbox_exec;
GRANT ALL ON ALL TABLES IN SCHEMA cron TO sandbox_exec;
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA cron TO sandbox_exec;
GRANT SELECT, REFERENCES, TRIGGER ON auth.users TO sandbox_exec;
GRANT USAGE ON SCHEMA auth, storage, extensions TO sandbox_exec;
GRANT ALL ON storage.objects TO sandbox_exec;
GRANT ALL ON storage.buckets TO sandbox_exec;